#!/usr/bin/env python
#
# Copyright (c) 2015 Catalyst.net Ltd
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

"""
Check that at least one one-wire temperature sensor responds on each bus of the given owfs path.

Michael Fincham <michael.fincham@catalyst.net.nz>.
"""

import argparse
import sys
import os
import subprocess

OWFS_PATH = "/srv/owfs"
TEMPERATURE_CHECK = "/usr/lib/nagios/plugins/check_onewire_temperatures"
BUS_COUNT = 2

NAGIOS_OK = 0
NAGIOS_WARNING = 1
NAGIOS_CRITICAL = 2
NAGIOS_UNKNOWN = 3

if __name__ == "__main__":

    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--owfs-path', metavar="PATH", type=str, default=OWFS_PATH, help='path to owfs filesystem, defaults to %s' % OWFS_PATH)
    parser.add_argument('--expected-bus-count', metavar="COUNT", type=int, default=BUS_COUNT, help='expected number of buses to find, defaults to %i' % BUS_COUNT)
    args = parser.parse_args()

    try:
        buses = [path for path in os.listdir(args.owfs_path) if path.startswith('bus.')]
    except:
        sys.stdout.write('error: no buses found at %s\n' % args.owfs_path)
        sys.exit(NAGIOS_UNKNOWN)

    if len(buses) < args.expected_bus_count:
        sys.stdout.write('%i buses missing (expected %i, found %i)\n' % ((args.expected_bus_count - len(buses)), args.expected_bus_count, len(buses)))
        sys.exit(NAGIOS_CRITICAL)

    FNULL = open(os.devnull, 'w')
    fails = []
    ok = []

    for bus in buses:
        if subprocess.check_call(('%s --owfs-path %s/%s' % (TEMPERATURE_CHECK, args.owfs_path, bus)).split(), stdout=FNULL, stderr=FNULL):
            fails.append(bus)
        else:
            ok.append(bus)

    if fails:
        sys.stdout.write("%i buses (%s) did not return any sensor data\n" % (len(fails), ', '.join(fails)))
        sys.exit(NAGIOS_CRITICAL)
    else:
        sys.stdout.write("%i buses OK\n" % len(ok))
        sys.exit(NAGIOS_OK)
